using CRM_ERP_UNID_TESTS;
using CRM_ERP_UNID.Data;

namespace Tests;

public class DatabaseSeeder
{
    public static void Seed(AppDbContext context)
    {
        context.Roles.AddRange(
            Models.Roles.Admin,
            Models.Roles.User,
            Models.Roles.Guest,
            Models.Roles.HighestPriority);
        context.Users.AddRange(
            Models.Users.Admin,
            Models.Users.InactiveTestUser,
            Models.Users.TestUser,
            Models.Users.TestUser2,
            Models.Users.HighestPriorityUser,
            Models.Users.DeactivateHighestPriorityUser,
            Models.Users.HighestPriorityUser2);
        context.UsersRoles.AddRange(
            Models.UsersRoles.AdminUserRoleAdmin,
            Models.UsersRoles.TestUserRoleUser,
            Models.UsersRoles.HighestPriorityUserRoleHighestPriority,
            Models.UsersRoles.DeactivateHighestPriorityUserRoleHighestPriority,
            Models.UsersRoles.HighestPriorityUserRoleHighestPriority2,
            Models.UsersRoles.TestUser2RoleUser);
        context.Permissions.AddRange(
            Models.Permissions.View,
            Models.Permissions.ViewReports,
            Models.Permissions.EditContent,
            Models.Permissions.Create,
            Models.Permissions.Delete,
            Models.Permissions.DeactivateUser,
            Models.Permissions.ActivateUser,
            Models.Permissions.Assign,
            Models.Permissions.Revoke);
        context.Resources.AddRange(
            Models.Resources.SuppliersBranches,
            Models.Resources.SuppliersProducts,
            Models.Resources.Suppliers,
            Models.Resources.Users,
            Models.Resources.Roles,
            Models.Resources.Permissions,
            Models.Resources.UsersRoles,
            Models.Resources.RolesPermissionsResources,
            Models.Resources.ResourcesResource,
            Models.Resources.ProductsResource,
            Models.Resources.BrandsResource,
            Models.Resources.InventoryResource,
            Models.Resources.BranchesResource,
            Models.Resources.UsersBranches);
        context.RolesPermissionsResources.AddRange(Models.RolesPermissionsResources.AdminViewUsers,
            Models.RolesPermissionsResources.AdminDeactivateUser,
            Models.RolesPermissionsResources.AdminEditContentUsers,
            Models.RolesPermissionsResources.AdminEditContent,
            Models.RolesPermissionsResources.AdminCreateUsers,
            Models.RolesPermissionsResources.AdminAssignRole,
            Models.RolesPermissionsResources.AdminRevokeRole,
            Models.RolesPermissionsResources.AdminViewUsersRoles,
            Models.RolesPermissionsResources.AdminAssignPermission,
            Models.RolesPermissionsResources.AdminRevokePermission,
            Models.RolesPermissionsResources.AdminViewRolesPermissionsResources,
            Models.RolesPermissionsResources.AdminEditRoles,
            Models.RolesPermissionsResources.AdminViewRoles,
            Models.RolesPermissionsResources.AdminCreateRoles,
            Models.RolesPermissionsResources.AdminDeleteRoles,
            Models.RolesPermissionsResources.AdminViewResources,
            Models.RolesPermissionsResources.AdminViewPermissions,
            Models.RolesPermissionsResources.AdminActivateUser,
            Models.RolesPermissionsResources.AdminViewProducts,
            Models.RolesPermissionsResources.AdminViewBrands,
            Models.RolesPermissionsResources.AdminCreateBrands,
            Models.RolesPermissionsResources.AdminEditBrands,
            Models.RolesPermissionsResources.AdminCreateProducts,
            Models.RolesPermissionsResources.AdminEditProducts,
            Models.RolesPermissionsResources.AdminCreateInventory,
            Models.RolesPermissionsResources.AdminEditInventory,
            Models.RolesPermissionsResources.AdminViewInventory,
            Models.RolesPermissionsResources.AdminViewBranches,
            Models.RolesPermissionsResources.AdminCreateBranches,
            Models.RolesPermissionsResources.AdminEditBranches,
            Models.RolesPermissionsResources.AdminAssignBranch,
            Models.RolesPermissionsResources.AdminRevokeBranch,
            Models.RolesPermissionsResources.AdminViewUsersBranches,
            Models.RolesPermissionsResources.AdminViewSuppliers,
            Models.RolesPermissionsResources.AdminEditContentSuppliers,
            Models.RolesPermissionsResources.AdminCreateSuppliers,
            Models.RolesPermissionsResources.AdminAssignProducts,
            Models.RolesPermissionsResources.AdminRevokeProducts,
            Models.RolesPermissionsResources.AdminViewSuppliersProducts,
            Models.RolesPermissionsResources.AdminAssignSupplierBranch,
            Models.RolesPermissionsResources.AdminRevokeSupplierBranch,
            Models.RolesPermissionsResources.AdminViewSuppliersBranches,
            Models.RolesPermissionsResources.AdminEditContentSuppliersBranches,
            Models.RolesPermissionsResources.AdminEditContentSuppliersProducts);
        context.RefreshTokens.AddRange(
            Models.RefreshTokens.TestUserRefreshTokenRevoked,
            Models.RefreshTokens.TestUserExpiredRefreshToken);
        context.PasswordRecoveryTokens.AddRange(
            Models.PasswordRecoveryTokens.TestValidTokenAsync,
            Models.PasswordRecoveryTokens.TestExpiredTokenAsync);
        context.Brands.AddRange(
            Models.Brands.Apple,
            Models.Brands.Samsung,
            Models.Brands.Nike);
        context.Products.AddRange(
            Models.Products.iPhone13,
            Models.Products.GalaxyS21,
            Models.Products.MacBookPro,
            Models.Products.iPadPro,
            Models.Products.GalaxyTabS7,
            Models.Products.SamsungQLEDTV,
            Models.Products.NikeAirMax270,
            Models.Products.NikeZoomX,
            Models.Products.NikeDriFitTShirt);
        context.Branches.AddRange(
            Models.Branches.HermosilloMiguelHidalgo,
            Models.Branches.CampoReal,
            Models.Branches.PuertoRico);
        context.Inventory.AddRange(
            Models.InventoryModels.iPhone13InventoryHermosillo,
            Models.InventoryModels.MacBookProInventoryHermosillo,
            Models.InventoryModels.iPadProInventoryHermosillo,
            Models.InventoryModels.GalaxyS21InventoryHermosillo,
            Models.InventoryModels.iPadProInventoryCampoReal,
            Models.InventoryModels.GalaxyS21InventoryCampoReal,
            Models.InventoryModels.GalaxyTabS7InventoryCampoReal,
            Models.InventoryModels.SamsungQLEDTVInventoryCampoReal,
            Models.InventoryModels.NikeAirMax270InventoryCampoReal,
            Models.InventoryModels.NikeZoomXInventoryCampoReal);
        context.UsersBranches.AddRange(
            Models.UsersBranches.AdminUserBranchHermosillo,
            Models.UsersBranches.TestUserBranchHermosillo,
            Models.UsersBranches.HighestPriorityUserBranchHermosillo,
            Models.UsersBranches.DeactivateHighestPriorityUserBranchHermosillo,
            Models.UsersBranches.TestUser2BranchPuertoRico,
            Models.UsersBranches.InactiveTestUserBranchHermosillo,
            Models.UsersBranches.HighestPriorityUserBranchCampoReal);
        context.Suppliers.AddRange(
            Models.Suppliers.Apple,
            Models.Suppliers.Xataka);
        context.SuppliersProducts.AddRange(
            Models.SuppliersProducts.AppleIphone13);
        context.SuppliersBranches.AddRange(
            Models.SuppliersBranches.AppleHermosilloMiguelHidalgo,
            Models.SuppliersBranches.ApplePuertoRico);

    context.SaveChanges();
     }
}